### ISSUE TITLE
Miss due Full Set

### ISSUE THREAD

**Issue by tomasalvarez13** [IIC2343/syllabus-2021-1#50]
Hola, tengo una duda sobre que significa el Miss due Full Set que arroja el emulador, no entiendo bien a que se refiere. ¿Significa que el bloque de la cache donde esta buscando esta ocupado por otro valor que no es el que necesito?

**Comment by tocococa** [comment]
Hola @tomasalvarez13 !

Si te refieres a lo que aparece en el log del simulador de caché, esto se debe a que un miss puede ocurrir principalmente por cuatro motivos:

1. Compulsory miss: ocurren porque el programa recién está iniciando y no tiene datos propios en caché o esta está vacía, estos aparecen como `empty -- MISS` en el log.
2. Conflict miss: ocurren cuando más de un bloque está mapeado al mismo set o bloque en el caché, y se trata de leer un dato mapeado a dicho caché, pero este ya está ocupado por otro bloque de memoria. Esto es lo que en el log aparece como `0x<address> -- OCCUPIED`, `MISS due to FULL SET`
3. Capacity miss: ocurren cuando el set de trabajo del programa es mayor al tamaño del caché. Este tipo de miss también debiese ocasionar que se imprima el mensaje `0x<address> -- OCCUPIED`, `MISS due to FULL SET`, ya que no queda espacio para guardar toda la información que sería útil tener en caché.
4. Coherence miss: cuando se tiene más de un procesador y el dato almacenado en caché no es válido, que no podemos ver en nuestros programas porque no son paralelos.
